### ISSUE TITLE
Mesh data storage for parallel use

### ISSUE THREAD

**Issue by JorisCaze** [LoicMarechal/libMeshb#13]
Dear Loic, 

I am interested to use your library in a CFD-code to read corresponding *.mesh* and *.meshb* mesh files but I have some questions left about parallel mesh.
 
I have seen that some softwares which use your mesh format give the final mesh splitted (one for each cpu) but it seems that each mesh file does not contain information about his *cpu number* and *cpu friend(s)* (for elements shared between cpu's or *ghost elements*). 

In the documentation, I found that there is the possibility to specify a *BeginLine/EndLine* for parallel reading in the section **GmfGetBlock**. Nonetheless, I am not sure it allows to read partioned mesh file and/or I don't have any clue on the way to proceed.

Therefore, what would be the *procedure* for reading partitioned meshes? 
I have the feeling that I missed something on the way the data is stored and if you could give some hints on that I would really appreciate.

Thank you for letting this library opensource and for your time.

**Comment by LoicMarechal** [comment]
Hi Joris,
the libMeshb was not designed for parallel I/O and the .meshb file format does not contain anything related to partitions or coloring.
Some people use it in their parallel code anyway but they developed their own parallel information structure on top of it.

The GetBlock procedure only allows you to specify the start and end indices to be read, the corresponding pointers to store the data in your own structures and an optional renumbering table to lay the data in an arbitrary order or position.
Some people use those capacities so that each process reads a subpart in a global mesh and renumber the entities to local indices through the optional table.

Regards,

Loïc

**Comment by tof92130** [comment]
I confirm, I am using lib meshb for block parallel reading then Cells are redistributed with parmetis ou pt-scotch. 

To write files, solutions are first merged then saved with libmeshb. 

Complementary libraries already exist to do all that stuff and make libmeshb fully parallel.

**Comment by JorisCaze** [comment]
Understood. Thank you for your detailed answer @LoicMarechal.
Thank you also @tof92130 for the additional explanations on the use of the mesh for a parallel purpose.

Regards, 

Joris
