### ISSUE TITLE
New dependency to librt

### ISSUE THREAD

**Issue by srpgilles** [LoicMarechal/libMeshb#17]
I have updated the libmeshb used with my code, and it resulted in a link error in most (but not all...) architectures in which I tried to use the new version.

The reason is an extra dependency to librt, probably introduced in commit 6d6ea14aaf95baad7a32eb1d0d35c294e44b24fa.

It would be nice to document explicitly this dependency 😉

**Comment by LoicMarechal** [comment]
Hi, did you compile with the WITH_AIO option enabled ?
The default setup is not to use the AIO because of this extra dependency that is missing on some older systems.
But I realize that I did not write anything about the WITH_AIO option in the documentation...
I will at it to my todolist.
Thanks for pointing this out.
Loïc

**Comment by srpgilles** [comment]
I’ll try it and see if I can avoid the explicit addition to librt in my code.
 However if the option was not activated it would be better that the related code is not compiled at all (this would avoid the linking mistake in the client code). Of course seems even better to use this if it optimizes the code 😃

best regards,

sebastien

**Comment by LoicMarechal** [comment]
Hi,
default behavior is not to use any async or low level I/O.
These features are only enabled and compiled with setting -DWITH_GMF_AIO.
The need to add -lrt at link time is explained in the documentation.

Regards,

Loïc
